apiVersion: v1
kind: Pod
metadata:
  name: learning-app
  labels:
    app: learning-app
spec:
  containers:
    - name: backend
      image: learning-app-backend:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8000

    - name: frontend
      image: learning-app-frontend:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: learning-app
spec:
  type: NodePort
  selector:
    app: learning-app
  ports:
    - name: frontend
      port: 5173
      targetPort: 5173
      nodePort: 30173
    - name: backend
      port: 8000
      targetPort: 8000
      nodePort: 30080
